### ISSUE TITLE
MyAnimeList Auth Error

### ISSUE THREAD

**Issue by ar664** [SwagOtaku/plugin.video.kaito#103]
I copied and pasted the link, but I get this error in the logs. Both the old and beta have this problem. I assume mal updated their api?

```
2022-01-31 20:57:33.181 T:11784   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\RiosFamily\AppData\Roaming\Kodi\addons\plugin.video.kaito\default.py", line 457, in <module>
                                                       router_process(g.PATH[1:], g.REQUEST_PARAMS)
                                                     File "C:\Users\RiosFamily\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\ui\router.py", line 71, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\Users\RiosFamily\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\WatchlistIntegration.py", line 42, in WL_LOGIN_MAL
                                                       return get_auth_dialog("mal")
                                                     File "C:\Users\RiosFamily\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\WatchlistIntegration.py", line 32, in get_auth_dialog
                                                       return WatchlistFlavor.login_request(flavor)
                                                     File "C:\Users\RiosFamily\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\WatchlistFlavor\__init__.py", line 91, in login_request
                                                       flavor_class.login(),
                                                     File "C:\Users\RiosFamily\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\WatchlistFlavor\MyAnimeList.py", line 42, in login
                                                       user = requests.get('https://api.myanimelist.net/v2/users/@me?fields=name', headers=self.__headers()).json()
                                                     File "C:\Users\RiosFamily\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 900, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
```

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry the developer is kinda dead at this moment and hope he and his family is doing ok this year. Anyway logged in to MAL just fine, the only problem im having is Kitsu cause menu items are not working correctly and if you log into all 3 watchlist and play a specific popular anime and stop it, it will give an error. Idk why and i think its due to watchlist. Anyway, hope your issue with MAL gets resolved soon.

**Comment by Goldenfreddy0703** [comment]
Hey so i actually got everything working, all i had to do was to clear cache and rebuild databases and all, its all good.

**Comment by Goldenfreddy0703** [comment]
Wow this is a year old issue lol. 😂

Come to Otaku, its basically Kaito but is maintained and has more features. 
https://github.com/Goldenfreddy0703/Otaku
