### ISSUE TITLE
Kaito keep crashing since updating to 0.0.6 (kodi 18.6 and 18.9)

### ISSUE THREAD

**Issue by FiFeX** [SwagOtaku/plugin.video.kaito#19]
The log:
```
2020-12-07 12:17:37.762 T:6268   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xd7 in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.kaito\default.py", line 363, in <module>
                                                _add_last_watched()
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.kaito\default.py", line 42, in _add_last_watched
                                                "%s[I]%s[/I]" % (control.lang(30000), last_watched['name']),
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by DaisyF8** [comment]
You should clear to defaults. It states above that when adding some Last Watched-info it finds an unsupported character.

It's probably an anime in (one of) your watchlist(s).  Hopefully if you re-authorize it will be able to deal with the error.

**Comment by FiFeX** [comment]
> 
> 
> You should clear to defaults. It states above that when adding some Last Watched-info it finds an unsupported character.
> 
> It's probably an anime in (one of) your watchlist(s). Hopefully if you re-authorize it will be able to deal with the error.

I reinstalled it, and it works,but as soon as I watch 1 episode, it crashes and refuses to work again. so...yeah,that a bit of a problem.. (the same error appears at the log file)

**Comment by SwagOtaku** [comment]
@FiFeX what show are you trying to watch?

**Comment by SwagOtaku** [comment]
a character in the anime title most likely is triggering this issue

**Comment by FiFeX** [comment]
It doesn't matter what, I choose a random anime from one of the "hot now" menus to try if it works.
I can test it on a specific show if you like me to.
