### ISSUE TITLE
Can't reach to the episode menus at shows I reach from search  - shows from other menus works fine

### ISSUE THREAD

**Issue by FiFeX** [SwagOtaku/plugin.video.kaito#29]
log:
```
2021-01-01 22:51:57.650 T:17164   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.kaito\default.py", line 365, in <module>
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.kaito\resources\lib\ui\router.py", line 68, in router_process
                                                return route_obj.func(payload, params)
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.kaito\default.py", line 125, in ANIMES_PAGE
                                                anime_general, content = _BROWSER.get_anime_init(anilist_id, filter_lang)
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.kaito\resources\lib\KaitoBrowser.py", line 128, in get_anime_init
                                                trakt_id = trakt.TRAKTAPI().get_trakt_id(name)
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.kaito\resources\lib\indexers\trakt.py", line 124, in get_trakt_id
                                                result = self._json_request(url)
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.kaito\resources\lib\indexers\trakt.py", line 23, in _json_request
                                                response = response.json()
                                              File "D:\Program Files\Kodi\portable_data\addons\script.module.requests\lib\requests\models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "D:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "D:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "D:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2021-01-01 22:51:57.708 T:5904   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kaito/animes/5680/5680/
2021-01-01 22:51:57.713 T:13148   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kaito/animes/5680/5680/) failed
```

**Comment by SwagOtaku** [comment]
trakt is having issues currently, need to wait for trakt to be back up

**Comment by FiFeX** [comment]
> 
> 
> trakt is having issues currently, need to wait for trakt to be back up

OK, ill try to remember to check it again in a day or two, thanks

**Comment by SwagOtaku** [comment]
trakt is stable now, if you get this error in log again check here for trakt status https://status.trakt.tv/
