### ISSUE TITLE
Everything MAL related stopped working

### ISSUE THREAD

**Issue by simpsil** [SwagOtaku/plugin.video.kaito#55]
im using kodi 18.9 i did clear cacha and im still getting an error that i should check log

**Comment by Sk0ppes** [comment]
Then check the log and post it here.

**Comment by simpsil** [comment]
2021-03-24 18:55:34.144 T:17534   ERROR: Window Translator: Can't find window infodialog
2021-03-24 18:55:35.197 T:17668   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
                                              'The soupsieve package is not installed. CSS selectors cannot be used.'
2021-03-24 18:55:36.147 T:17534   ERROR: Window Translator: Can't find window infodialog
2021-03-24 18:55:39.011 T:17675   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
                                              'The soupsieve package is not installed. CSS selectors cannot be used.'
2021-03-24 18:55:44.132 T:17681   ERROR: Previous line repeats 1 times.
2021-03-24 18:55:44.132 T:17681   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'data'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/default.py", line 365, in <module>
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/ui/router.py", line 68, in router_process
                                                return route_obj.func(payload, params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/WatchlistIntegration.py", line 52, in WATCHLIST_STATUS_TYPE
                                                return control.draw_items(WatchlistFlavor.watchlist_status_request(flavor, status, params))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/WatchlistFlavor/__init__.py", line 60, in watchlist_status_request
                                                return WatchlistFlavor.__instance_flavor(name).get_watchlist_status(status, next_up)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/WatchlistFlavor/MyAnimeList.py", line 108, in get_watchlist_status
                                                return self._process_status_view(url, params, next_up, "watchlist_status_type_pages/mal/%s/%%s/%%d" % status, page)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/WatchlistFlavor/MyAnimeList.py", line 137, in _process_status_view
                                                all_results = map(self._base_watchlist_status_view, results['data'])
                                            KeyError: 'data'
                                            -->End of Python script error report<--
2021-03-24 18:55:44.324 T:17680   ERROR: GetDirectory - Error getting plugin://plugin.video.kaito/watchlist_status_type/mal/watching
2021-03-24 18:55:44.328 T:17476   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kaito/watchlist_status_type/mal/watching) failed
2021-03-24 18:55:48.904 T:17692   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
                                              'The soupsieve package is not installed. CSS selectors cannot be used.'
2021-03-24 18:55:50.103 T:17692   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'data'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/default.py", line 365, in <module>
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/ui/router.py", line 68, in router_process
                                                return route_obj.func(payload, params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/WatchlistIntegration.py", line 52, in WATCHLIST_STATUS_TYPE
                                                return control.draw_items(WatchlistFlavor.watchlist_status_request(flavor, status, params))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/WatchlistFlavor/__init__.py", line 60, in watchlist_status_request
                                                return WatchlistFlavor.__instance_flavor(name).get_watchlist_status(status, next_up)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/WatchlistFlavor/MyAnimeList.py", line 108, in get_watchlist_status
                                                return self._process_status_view(url, params, next_up, "watchlist_status_type_pages/mal/%s/%%s/%%d" % status, page)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kaito/resources/lib/WatchlistFlavor/MyAnimeList.py", line 137, in _process_status_view
                                                all_results = map(self._base_watchlist_status_view, results['data'])
                                            KeyError: 'data'
                                            -->End of Python script error report<--
2021-03-24 18:55:50.304 T:17691   ERROR: GetDirectory - Error getting plugin://plugin.video.kaito/watchlist_status_type/mal/plan_to_watch
2021-03-24 18:55:50.308 T:17476   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kaito/watchlist_status_type/mal/plan_to_watch) failed
2021-03-24 18:55:52.423 T:17499 WARNING: Repository add-on repository.elementum uses plain HTTP for add-on downloads in path http://127.0.0.1:65220/repository/elgatito/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!

**Comment by simpsil** [comment]
what part should i post?

**Comment by ctanom** [comment]
I can't get any results to return at all unfortunately been happening for about 2 days. Kodi 18.9 tried reinstalling everything etc

**Comment by simpsil** [comment]
> 
> 
> I can't get any results to return at all unfortunately been happening for about 2 days. Kodi 18.9 tried reinstalling everything etc

yea im on the same boat

**Comment by Prometheusx-git** [comment]
It is a problem with the updated beautifulsoup4-4.9.3.
You need to install the old version beautifulsoup4-4.6.2.zip, then the search works again.

**Comment by jorgemlferreira** [comment]
Hi. Don't want to open another issue since I'm having a similar problem. After I copy the link, it displays the message invalid username or password for mal authentication. What am I doing wrong? I'm on kodi 19
