### ISSUE TITLE
[Bug] Update Watchlist Kitsu gives an error when playing an anime. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SwagOtaku/plugin.video.kaito#59]
Hey, really quick, i found an error in the watchlist category if you Update Watchlist to Kitsu, you will get an error when you play an anime.  

Here is the Log error it gives and thats the only error i found so far but everything else is amazing. 

```
2021-04-05 01:52:37.195 T:9312     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.kaito/play/124080/1/
2021-04-05 01:52:37.666 T:4332     INFO <general>: Creating InputStream
2021-04-05 01:52:37.787 T:1640    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'data'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\default.py", line 366, in <module>
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\ui\router.py", line 68, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\default.py", line 314, in PLAY
                                                       player.play_source(link,
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\ui\player.py", line 296, in play_source
                                                       watchlistPlayer().handle_player(anilist_id, watchlist_update, build_playlist, episode, filter_lang)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\ui\player.py", line 60, in handle_player
                                                       self._watchlist_update = watchlist_update(anilist_id, episode)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\WatchlistIntegration.py", line 133, in watchlist_update
                                                       return WatchlistFlavor.watchlist_update_request(anilist_id, episode)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\WatchlistFlavor\__init__.py", line 71, in watchlist_update_request
                                                       return WatchlistFlavor.get_update_flavor().watchlist_update(anilist_id, episode)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\WatchlistFlavor\Kitsu.py", line 275, in watchlist_update
                                                       if len(item_dict['data']) == 0:
                                                   KeyError: 'data'
                                                   -->End of Python script error report<--
```

**Comment by Goldenfreddy0703** [comment]
Edit: Kitsu needed a re-login and real debrid was being dumb.
