### ISSUE TITLE
RealDebrid issue - python TypeError

### ISSUE THREAD

**Issue by lenslol** [SwagOtaku/plugin.video.kaito#65]
Cannot play episode, here is the error from the logfile

> 
> 2021-05-03 16:04:48.494 T:14160   ERROR: Traceback (most recent call last):
> 2021-05-03 16:04:48.494 T:14160   ERROR:   File "C:\Users\svvpa\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\debrid\real_debrid.py", line 260, in resolve_single_magnet
> 2021-05-03 16:04:48.494 T:14160   ERROR:     for storage_variant in hashCheck[hash_]['rd']:
> 2021-05-03 16:04:48.495 T:14160   ERROR: TypeError: string indices must be integers
> 2021-05-03 16:04:49.265 T:14160   ERROR: Traceback (most recent call last):
> 2021-05-03 16:04:49.265 T:14160   ERROR:   File "C:\Users\svvpa\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\debrid\real_debrid.py", line 260, in resolve_single_magnet
> 2021-05-03 16:04:49.265 T:14160   ERROR:     for storage_variant in hashCheck[hash_]['rd']:
> 2021-05-03 16:04:49.265 T:14160   ERROR: TypeError: string indices must be integers
> 2021-05-03 16:04:49.303 T:9672   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.kaito/play/106625/18/]
> 2021-05-03 16:04:49.303 T:9672 WARNING: Attempt to set unplayable index 0

**Comment by lenslol** [comment]
Also happening with AllDebrid

2021-05-03 16:51:53.197 T:12464   ERROR: Traceback (most recent call last):
2021-05-03 16:51:53.198 T:12464   ERROR:   File "C:\Users\svvpa\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\windows\resolver.py", line 130, in resolve_source
2021-05-03 16:51:53.198 T:12464   ERROR:     stream_link = api.resolve_single_magnet(hash_, magnet, source['episode_re'])
2021-05-03 16:51:53.198 T:12464   ERROR:   File "C:\Users\svvpa\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\debrid\all_debrid.py", line 175, in resolve_single_magnet
2021-05-03 16:51:53.198 T:12464   ERROR:     selected_files = sorted([idx for idx, i in enumerate(folder_details) if source_utils.get_best_match(episode, i['path'])])[0]
2021-05-03 16:51:53.198 T:12464   ERROR: TypeError: tuple indices must be integers, not str
2021-05-03 16:51:53.655 T:12464   ERROR: Traceback (most recent call last):
2021-05-03 16:51:53.655 T:12464   ERROR:   File "C:\Users\svvpa\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\windows\resolver.py", line 130, in resolve_source
2021-05-03 16:51:53.655 T:12464   ERROR:     stream_link = api.resolve_single_magnet(hash_, magnet, source['episode_re'])
2021-05-03 16:51:53.655 T:12464   ERROR:   File "C:\Users\svvpa\AppData\Roaming\Kodi\addons\plugin.video.kaito\resources\lib\debrid\all_debrid.py", line 175, in resolve_single_magnet
2021-05-03 16:51:53.655 T:12464   ERROR:     selected_files = sorted([idx for idx, i in enumerate(folder_details) if source_utils.get_best_match(episode, i['path'])])[0]
2021-05-03 16:51:53.655 T:12464   ERROR: TypeError: tuple indices must be integers, not str
2021-05-03 16:51:53.678 T:1272   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.kaito/play/106625/17/]
2021-05-03 16:51:53.678 T:1272 WARNING: Attempt to set unplayable index 0

**Comment by lenslol** [comment]
My apologies, this was due to the RealDebrid outage.
